name: "8-Bit Hustler"
description: "Ruby. JavaScript. Not necessarily in that order."

author: "Tian Davis"

url: "http://tiandavis.com"
baseurl: ""

markdown: rdiscount
permalink: :year/:month/:title.html
pygments: true

# Google Analytics
ga_domain: tiandavis.com
ga_tracking_id: UA-17961498-4
