name: "Tian Davis"
description: "Software should be beautiful & inspired."

author: "Tian Davis"

url: "http://tiandavis.com"
baseurl: ""

#markdown: rdiscount
markdown: kramdown
permalink: /thoughts/:year/:month/:title.html
#highlighter: pygments
highlighter: rouge

# Google Analytics
ga_domain: tiandavis.com
ga_tracking_id: UA-17961498-4
